### ISSUE TITLE
faster GLMs with speedglm

### ISSUE THREAD

**Issue by benkeser** [benkeser/survtmle#16] opened 2017-07-14 20:36 UTC
Adding `speedglm` to hazard-based estimation procedures (`estimateCensoring` and `estimateHazards`) may be beneficial to speed up run time. Oleg reports fairly frequent convergence errors with `speedglm`, so probably good to implement in using `try` as he did [here](https://github.com/osofr/gridisl/blob/master/R/ModelGLMsClass.R#L90-L103).

**Comment by nhejazi** [comment] 2017-07-14 20:41
last comment on [this SO thread](https://stackoverflow.com/questions/16284766/how-to-speed-up-glm-estimation-in-r) seems relevant

**Comment by benkeser** [comment] 2017-07-14 20:55
Using `sparseMatrix` representation seems promising, especially if it speeds up glm fitting considerably.

**Comment by benkeser** [comment] 2017-07-14 21:05
`sparse.model.matrix` seems pretty slow, but `speedglm.wfit` with sparse matrix objects is very fast (even with `family = "binomial"`). We should be able to figure out a smarter way to get a sparse matrix representation without invoking `sparse.model.matrix`.

**Comment by nhejazi** [comment] 2017-07-14 21:21
Ok, good to know, so the problem now is that we want to generate a sparse design matrix very quickly, and then simply pass that to `speedglm.wfit`

**Comment by nhejazi** [comment] 2017-07-14 21:26
@benkeser, do you have a minimal working example that you've been playing with? I can do a bit of testing...also, maybe [this answer](https://stackoverflow.com/questions/10822150/faster-way-to-set-up-a-sparse-matrix-in-r) might be faster than calling `sparse.model.matrix`? There's also [this package](https://cran.r-project.org/web/packages/slam/slam.pdf), which seems relevant.

**Comment by benkeser** [comment] 2017-07-14 21:36
Here's an example (just gutting survtmle to get the relevant objects to play with)
```{r}
set.seed(1234)
n <- 1000
t_0 <- 6
trt <- rbinom(n, 1, 0.5)
# e.g., study site
adjustVars <- data.frame(site = (rbinom(n,1,0.5) + 1))
ftime <- round(1 + runif(n, 1, 350) - trt + adjustVars$site)
ftype <- round(runif(n, 0, 1))

#' make a formula that will implement an empirical hazard
#' estimator when called in estimateHazard
get.ftimeForm <- function(trt, site){
	form <- "-1"
	for(i in unique(trt)){
		for(s in unique(site)){
			form <- c(form, 
			  paste0("I(trt==",i,"& site == ",s," & t==",
			         unique(ftime[ftype>0 & trt==i & site == s]),")",
			         collapse="+"))
		}
	}
	return(paste(form,collapse="+"))
}


#' make a formula that will implement an empirical hazard
#' estimator when called in estimateCensoring
get.ctimeForm <- function(trt, site){
	form <- "-1"
	for(i in unique(trt)){
		for(s in unique(site)){
			form <- c(form, 
			  paste0("I(trt==",i,"& site == ",s," & t==",
			         unique(ftime[ftype==0 & trt==i & site == s]),")",
			         collapse="+"))
		}
	}
	return(paste(form,collapse="+"))
}

glm.ftime <- get.ftimeForm(trt = trt, site = adjustVars$site)
glm.ctime <- get.ctimeForm(trt = trt, site = adjustVars$site)
# debug(hazard_tmle)
# fit <- survtmle(ftime = ftime, 
#                 ftype = ftype,
#                 trt = trt,
#                 adjustVars = adjustVars,
#                 glm.ftime = form.ftime,
#                 glm.ctime = form.ctime,
#                 glm.trt = "1", t0 = 300)
bounds <- NULL; SL.trt <- SL.ctime <- NULL
ftypeOfInterest <- 1; trtOfInterest <- c(0,1)
glm.trt <- "1"; gtol <- 1e-2; returnModels = FALSE
t0 <- 300
n <- length(ftime)
id <- seq_len(n)
dat <- data.frame(id = id, ftime = ftime, ftype = ftype, 
    trt = trt)
if (!is.null(adjustVars)) 
    dat <- cbind(dat, adjustVars)
nJ <- length(ftypeOfInterest)
allJ <- sort(unique(ftype[ftype != 0]))
ofInterestJ <- sort(ftypeOfInterest)
ntrt <- length(trtOfInterest)
uniqtrt <- sort(trtOfInterest)
trtOut <- survtmle:::estimateTreatment(dat = dat, ntrt = ntrt, uniqtrt = uniqtrt, 
    adjustVars = adjustVars, SL.trt = SL.trt, glm.trt = glm.trt, 
    returnModels = returnModels, gtol = gtol)
dat <- trtOut$dat
trtMod <- trtOut$trtMod
dataList <- survtmle:::makeDataList(dat = dat, J = allJ, ntrt = ntrt, 
    uniqtrt = uniqtrt, t0 = t0, bounds = bounds)
include <- !(dataList[[1]]$t == dataList[[1]]$ftime & dataList[[1]]$C != 
        1 & dataList[[1]]$t < t0) & !(dataList[[1]]$t == dataList[[1]]$ftime & 
        dataList[[1]]$C == 1 & dataList[[1]]$t == t0)


# glm formula
ctimeForm <- sprintf("%s ~ %s", "C", glm.ctime)
# can call with family = "gaussian" or replace with
# speed glm
ctimeMod <- glm(as.formula(ctimeForm), data = dataList[[1]][include, ], 
                family = "binomial")
```

**Comment by nhejazi** [comment] 2017-07-17 23:09
162f413 on branch `speedglm` implements a new wrapper function `fast_glm`, which should serve as a drop-in replacement for all uses of `glm` in the various `estimate...` functions.

`fast_glm` should be further fleshed out so that we can assess exactly to what degree we can speed up the various `glm` calls using `speedglm`...

Also, `fast_glm` currently leads to an error in compiling the package vignette -- this needs to be further investigated.

**Comment by nhejazi** [comment] 2017-07-18 22:08
29d0edb changes the new `fast_glm` function to default to using `speedglm`, but changes all instances of the wrapper being called to use the `glm` option. this avoids breaking changes. currently, use of `speedglm` creates weird errors when checking examples, including an LAPACK routine complaining about singular matrices...

**Comment by nhejazi** [comment] 2017-07-19 16:41
Some more thoughts on this @benkeser:
In almost every case where `glm` is called (with the notable exception of fitting the outcome regression `Qmod` in the function `estimateIteratedMean`), it is intended to perform logistic regression.

We can avoid some of the notational headache associated with use of the `speedglm` package by more directly using functions like [`fastLR`](https://rdrr.io/cran/RcppNumerical/man/fastLR.html) from [`RcppNumerical`](https://cran.r-project.org/web/packages/RcppNumerical/vignettes/introduction.html). Other avenues for improving the time for these model fitting procedures include calling `glm.fit` directly (which requires a model matrix as input) rather than the standard call to `glm` using the convenient formula notation.

**Comment by nhejazi** [comment] 2017-07-23 21:02
Trying some naive benchmarking:

adapting the MWE/setup given by @benkeser above:
```
library(speedglm)

# glm formula
R > ctimeForm <- sprintf("%s ~ %s", "C", glm.ctime)
R > ctimeForm_mod <- as.formula(ctimeForm)

R > t1 <- system.time(model.matrix(ctimeForm_mod, data = dataList[[1]][include,]))
R > t1
   user  system elapsed
 25.672   0.662  26.332

# can we get the matrix faster by using caret::dummyVars?
R > t2 <- system.time(caret::dummyVars(ctimeForm_mod, data = dataList[[1]][include,], fullRank=TRUE))
R > t2
   user  system elapsed
  5.725   0.000   5.726

# are the objects equivalent
R > m1 <- model.matrix(ctimeForm_mod, data = dataList[[1]][include,])
R > m2 <- caret::dummyVars(ctimeForm_mod, data = dataList[[1]][include,], fullRank=TRUE)
R > all.equal(m1,m2)
[1] "Modes: numeric, list"
[2] "Lengths: 72175038, 9"
[3] "names for current but not for target"
[4] "Attributes: < Names: 1 string mismatch >"
[5] "Attributes: < Length mismatch: comparison on first 1 components >"
[6] "Attributes: < Component 1: Modes: numeric, character >"
[7] "Attributes: < Component 1: Lengths: 433, 1 >"
[8] "Attributes: < Component 1: target is numeric, current is character >"
[9] "target is matrix, current is dummyVars"

# does this difference matter?
t_fit1 <- system.time(glm(C ~ m1, data = dataList[[1]][include,], family = "binomial"))
t_fit2 <- system.time(glm(C ~ m2, data = dataList[[1]][include,], family = "binomial"))

# does using speedglm help?
t_fit3 <- system.time(speedglm(C ~ m1, data = dataList[[1]][include,], family = stats::binomial()))
t_fit4 <- system.time(speedglm(C ~ m2, data = dataList[[1]][include,], family = stats::binomial()))

# construct the objects...
fit1 <- glm(C ~ m1, data = dataList[[1]][include,], family = "binomial")
fit2 <- glm(C ~ m2, data = dataList[[1]][include,],family = "binomial")
fit3 <- speedglm(C ~ m1, data = dataList[[1]][include,], family = stats::binomial())
fit4 <- speedglm(C ~ m2, data = dataList[[1]][include,], family = stats::binomial())

# should we bother with RcppNumerical
library(RcppNumerical)
y <- dataList[[1]][include,"C"]
fit5 <- fastLR(x = m1, y = y)
t_fit5 <- system.time(fastLR(x = m1, y = y))
```

__Resources:__
* [SO: faster model matrices](https://stackoverflow.com/questions/31373710/r-fast-way-to-create-a-sparse-model-matrix)
* [SO: `glm` with model matrices in R](https://stackoverflow.com/questions/31373710/r-fast-way-to-create-a-sparse-model-matrix)

**Comment by nhejazi** [comment] 2017-07-23 21:35
__preliminary results, continuing from the above__

recall the time associated with creating a `model.matrix` object:
```
R > t1 <- system.time(model.matrix(ctimeForm_mod, data = dataList[[1]][include,]))
R > t1
   user  system elapsed
 25.672   0.662  26.332
```

_`glm` with regular `model.matrix`_:
```
R > t_fit1 <- system.time(glm(C ~ m1, data = dataList[[1]][include,], family = "binomial"))
R > t_fit1
   user  system elapsed
741.639   8.558 750.098
```

_`speedglm` with regular `model.matrix`_:
```
R > t_fit3 <- system.time(speedglm(C ~ m1, data = dataList[[1]][include,], family = stats::binomial()))
R > t_fit3
   user  system elapsed
 68.787  12.660  81.436
```

_using `fastLR` from the `RcppNumerical` package_:
```
R > y <- dataList[[1]][include,"C"]
R > fit5 <- fastLR(x = m1, y = y)
R > t_fit5 <- system.time(fastLR(x = m1, y = y))
R > t_fit5
   user  system elapsed
 31.517   0.006  31.521
```

**Comment by nhejazi** [comment] 2017-07-23 23:21
Finishing up this benchmarking experiment
```
R > t19 <- system.time(fit19 <- speedglm(as.formula(ctimeForm), data = dataList[[1]][include,],family = stats::binomial()))
R > t19
   user  system elapsed
 84.396   8.279  92.661
R > t20 <- system.time(fit20 <- glm(as.formula(ctimeForm), data = dataList[[1]][include,],family = stats::binomial()))
R > t20
   user  system elapsed
724.696   5.223 729.814
R > t20["elapsed"] / t19["elapsed"]
 elapsed
7.876172
```
Almost an order-of-magnitude speedup, just using `speedglm` naively...

**Comment by nhejazi** [comment] 2017-07-24 00:19
631c0d8 fixes the wrapper funciton `fast_glm`, allowing for `speedglm` to be invoked correctly, though this does not play well with `timepoints`. See #18 for details.

**Comment by nhejazi** [comment] 2017-07-28 00:35
Elementary benchmarking of `master` and `speedglm` using the following example:
```
# simulate data
set.seed(341796)
n <- 100
t_0 <- 10
W <- data.frame(W1 = runif(n), W2 = rbinom(n, 1, 0.5))
A <- rbinom(n, 1, 0.5)
T <- rgeom(n,plogis(-4 + W$W1 * W$W2 - A)) + 1
C <- rgeom(n, plogis(-6 + W$W1)) + 1
ftime <- pmin(T, C)
ftype <- as.numeric(ftime == T)
```

__Result from `master`:__
```
❯ system.time(
... fit <- survtmle(ftime = ftime, ftype = ftype,
...                  trt = A, adjustVars = W,
...                  glm.trt = "1",
...                  glm.ftime = "I(W1*W2) + trt + t",
...                  glm.ctime = "W1 + t", method = "hazard",
...                  t0 = t_0)
... )
   user  system elapsed
  0.360   0.016   0.408
```

__Result from `speedglm`:__
```
❯ system.time(
... fit <- survtmle(ftime = ftime, ftype = ftype,
...                  trt = A, adjustVars = W,
...                  glm.trt = "1",
...                  glm.ftime = "I(W1*W2) + trt + t",
...                  glm.ctime = "W1 + t", method = "hazard",
...                  t0 = t_0)
... )
'speedglm' ran into an error in estimateHazards ... using 'glm' instead.
   user  system elapsed 
  0.580   0.048   0.721
```

**Comment by nhejazi** [comment] 2017-08-01 21:39
Further benchmarking appears to indicate that `speedglm` does afford some timing advantages over standard `glm` when sample sizes are larger (e.g., n = 1000+ v. n = 100). See the discussion and Jupyter notebooks in #19 for a more thorough benchmarking analysis.

**Comment by nhejazi** [comment] 2017-08-11 14:50
`speedglm` currently fails in both `estimateTreatment` and `estimateCensoring`.

Here's the relevant error and `traceback()` from a call to `speedglm` in `estimateCensoring`:
```
R > test <- speedglm(formula = reg_form, data = dat, family = family, fitted = TRUE)
Error in structure(x, class = unique(c("AsIs", oldClass(x)))) :
  object 'site' not found
Did you mean : setIs or exists ?
R > traceback()
8: structure(x, class = unique(c("AsIs", oldClass(x))))
7: I(trt == 0 & site == 2 & t == 148)
6: eval(predvars, data, env)
5: eval(predvars, data, env)
4: model.frame.default(Terms, newdata, na.action = na.action)
3: model.frame(Terms, newdata, na.action = na.action)
2: predict.speedlm(rval, newdata = M)
1: speedglm(formula = reg_form, data = dat, family = family, fitted = TRUE)
```

**Comment by benkeser** [comment] 2017-08-11 14:57
The error means R is looking for an object `site`, which makes me think we're missing quotations somewhere. What does `reg_form` and `head(dat)` look like?

**Comment by benkeser** [comment] 2017-08-11 15:00
Is `dat` a `data.frame` with a column named `site`? If so, it seems like `model.frame` should be able to find it...

**Comment by nhejazi** [comment] 2017-08-11 15:03
sorry, I should have added context for that...
The example comes from the 7th comment on this thread, where you gave an example to try out

```
reg_form = ctimeForm
dat <- dataList[[1]][include,]

R > head(dat)
    id ftime ftype trt site   g_1   g_0 N1 C t l1 u1
1.0  1    44     1   0    2 0.518 0.482  0 0 4  0  1
1.1  1    44     1   0    2 0.518 0.482  0 0 5  0  1
1.2  1    44     1   0    2 0.518 0.482  0 0 6  0  1
1.3  1    44     1   0    2 0.518 0.482  0 0 7  0  1
1.4  1    44     1   0    2 0.518 0.482  0 0 8  0  1
1.5  1    44     1   0    2 0.518 0.482  0 0 9  0  1
```

**Comment by benkeser** [comment] 2017-08-11 15:09
I'm getting a different error when I run that code with the most recent commit on the speedglm branch.

**Comment by nhejazi** [comment] 2017-08-11 15:09
The plot thickens...apparently, the following (adapted from code in `stremr`) works, but I've not yet confirmed that the returned object meets our needs:
```
R > system.time(test2 <- speedglm(formula = reg_form, data = dat, family = family, method = "Cholesky", trace = FALSE))
   user  system elapsed
 96.492  25.489 122.696
```

update, adding a mwe @benkeser, hopefully this returns the same error on your end:
```
set.seed(1234)
n <- 1000
t_0 <- 6
trt <- rbinom(n, 1, 0.5)
# e.g., study site
adjustVars <- data.frame(site = (rbinom(n,1,0.5) + 1))
ftime <- round(1 + runif(n, 1, 350) - trt + adjustVars$site)
ftype <- round(runif(n, 0, 1))

#' make a formula that will implement an empirical hazard
#' estimator when called in estimateHazard
get.ftimeForm <- function(trt, site){
	form <- "-1"
	for(i in unique(trt)){
		for(s in unique(site)){
			form <- c(form, 
			  paste0("I(trt==",i,"& site == ",s," & t==",
			         unique(ftime[ftype>0 & trt==i & site == s]),")",
			         collapse="+"))
		}
	}
	return(paste(form,collapse="+"))
}


#' make a formula that will implement an empirical hazard
#' estimator when called in estimateCensoring
get.ctimeForm <- function(trt, site){
	form <- "-1"
	for(i in unique(trt)){
		for(s in unique(site)){
			form <- c(form, 
			  paste0("I(trt==",i,"& site == ",s," & t==",
			         unique(ftime[ftype==0 & trt==i & site == s]),")",
			         collapse="+"))
		}
	}
	return(paste(form,collapse="+"))
}

glm.ftime <- get.ftimeForm(trt = trt, site = adjustVars$site)
glm.ctime <- get.ctimeForm(trt = trt, site = adjustVars$site)
# debug(hazard_tmle)
# fit <- survtmle(ftime = ftime, 
#                 ftype = ftype,
#                 trt = trt,
#                 adjustVars = adjustVars,
#                 glm.ftime = form.ftime,
#                 glm.ctime = form.ctime,
#                 glm.trt = "1", t0 = 300)
bounds <- NULL; SL.trt <- SL.ctime <- NULL
ftypeOfInterest <- 1; trtOfInterest <- c(0,1)
glm.trt <- "1"; gtol <- 1e-2; returnModels = FALSE
t0 <- 300
n <- length(ftime)
id <- seq_len(n)
dat <- data.frame(id = id, ftime = ftime, ftype = ftype, 
    trt = trt)
if (!is.null(adjustVars)) 
    dat <- cbind(dat, adjustVars)
nJ <- length(ftypeOfInterest)
allJ <- sort(unique(ftype[ftype != 0]))
ofInterestJ <- sort(ftypeOfInterest)
ntrt <- length(trtOfInterest)
uniqtrt <- sort(trtOfInterest)
trtOut <- survtmle:::estimateTreatment(dat = dat, ntrt = ntrt, uniqtrt = uniqtrt, 
    adjustVars = adjustVars, SL.trt = SL.trt, glm.trt = glm.trt, 
    returnModels = returnModels, gtol = gtol)
dat <- trtOut$dat
trtMod <- trtOut$trtMod
dataList <- survtmle:::makeDataList(dat = dat, J = allJ, ntrt = ntrt, 
    uniqtrt = uniqtrt, t0 = t0, bounds = bounds)
include <- !(dataList[[1]]$t == dataList[[1]]$ftime & dataList[[1]]$C != 
        1 & dataList[[1]]$t < t0) & !(dataList[[1]]$t == dataList[[1]]$ftime & 
        dataList[[1]]$C == 1 & dataList[[1]]$t == t0)


# glm formula
ctimeForm <- sprintf("%s ~ %s", "C", glm.ctime)

# set up GLMs
glm.family <- "binomial"
if (!is.null(glm.family)) {
    glm_family <- parse(text = paste0("stats::", glm.family, "()"))
 }

reg_form = ctimeForm
dat <- dataList[[1]][include,]
family <- eval(glm_family)
```

**Comment by benkeser** [comment] 2017-08-11 15:12
Interesting... I've gotten the error to reproduce and am looking further into the guts of `speedlm`. The Cholesky decomposition is probably fine for our purposes, if my first-year-of-grad-school memories serve me right...

**Comment by nhejazi** [comment] 2017-08-11 15:14
Ok, so on the page re: errors. I have a feeling that it's the arguments `trace` and `fitted` that might be causing trouble

**Comment by benkeser** [comment] 2017-08-11 15:16
At first blush, it seems to be that `speedlm` does not play nicely with formulas input with `I()`. It seems to be trying to do something stupid to get fitted values. Removing `fitted = TRUE` seems to fix.

**Comment by nhejazi** [comment] 2017-08-11 15:18
Ok, thanks for digging into that and confirming. If I recall, `fitted = TRUE` was added because it allows us to use the model to predict later ~~(vaguely, I remember something about `speedglm` lacking a proper `predict.speedglm` method...)~~ <- I was wrong

**Comment by benkeser** [comment] 2017-08-11 15:18
If `fitted = TRUE`, `speedlm` calls `predict.speedlm`, which tries to run this line:

```r
    m <- model.frame(Terms, newdata, na.action = na.action)
```

but `newdata` is a `data.frame` that was output by a previous call to `model.frame` and thus is not compatible with `Terms`.

Seems like a bug in `speedlm`. Is there a reason to return the fitted values in a single call to `speedlm`?

**Comment by benkeser** [comment] 2017-08-11 15:20
Based on the help file, it seems that fitted would just return values for dataList[[1]][include,], but we'd still need to predict on new data (e.g., `dataList[[i]]` for i = 1,...,`length(dataList)`).

**Comment by nhejazi** [comment] 2017-08-11 15:21
Alright, good to know that this is the source of the error. Seems odd that they wouldn't have caught a general situation like that it a test...

I don't recall offhand why I had set `fitted = TRUE`; I'll investigate further.

__update:__ Not that we needed it, but I think this pretty much confirms that `fitted = TRUE` (and specifically the line you highlighted above @benkeser) is the culprit
```
system.time(test3 <- speedglm(formula = reg_form, data = dat, family = family, method = "Cholesky", sparse=TRUE, fitted = TRUE, trace = FALSE))
Error in structure(x, class = unique(c("AsIs", oldClass(x)))) :
  object 'site' not found
Did you mean : setIs or exists ?
Timing stopped at: 95.8 66.56 163.8
```

**Comment by benkeser** [comment] 2017-08-11 15:23
This seems to work:
```r
test <- speedglm(formula = reg_form, data = dat, family = gaussian())
newdata <- data.frame(t = c(2,4,6), trt = c(0,1,0), site = c(1,1,2))
tmp <- predict(test, newdata = newdata)
tmp
```

**Comment by benkeser** [comment] 2017-08-11 15:25
I think we can go with `method = "Cholesky"` too. 

From `?speedglm:::control`:
The "Cholesky" method is faster than "eigen" and does not use tolerance, but the former seems to be more stable for opportune tolerance values.

We shouldn't be running into nearly singular matrices in these applications, so would be OK to go with the faster check for singularity.

**Comment by nhejazi** [comment] 2017-08-11 15:25
Makes sense. I'll look into changing `fast_glm` and its usage to incorporate use of the `predict` method for these classes (I can't for the life of me now remember why I had `fitted = TRUE` in the first place). Sounds good, `cholesky` it is.

**Comment by nhejazi** [comment] 2017-08-11 15:29
Just curious -- given the size of the model formula, I'd expect the actual model matrix to be spare. Do we have any guarantee that this might generally be true?

If so, it does save us time (only a bit in this example, but might be nice generally):
```
R > system.time(test3 <- speedglm(formula = reg_form, data = dat, family = family, method = "Cholesky", sparse=TRUE, trace = FALSE))
   user  system elapsed
 97.213  15.177 112.380
R > system.time(test4 <- speedglm(formula = reg_form, data = dat, family = family, method = "Cholesky", trace = FALSE))
   user  system elapsed
 98.088  15.061 113.138
```

**Comment by benkeser** [comment] 2017-08-11 15:32
For the applications that I have in mind, yes, the matrix will generally be sparse.

**Comment by nhejazi** [comment] 2017-08-11 16:40
Current version of `fast_glm` (on branch `speedglm`) now works! It's notably faster than `glm` even on small data sets (n = 100); benchmarks in progress for larger data sets (n = 1000).

No more errors in `estimateCensoring` or `estimateHazards`, but there is a new (yet to be investigated) error in `estimateTreatment` now...

**Comment by nhejazi** [comment] 2017-08-20 21:18
3309d0b resolves the error in `estimateTreatment`, which was caused by specifying `sparse = TRUE` in a call to `speedglm::speedglm`. Obviously, the design matrix is not sparse when fitting an intercept model, which is all that `estimateTreatment` appears to do.

Closing this since #19 is ready to be merged. Feel free to re-open if there is more to be done here.

**Closed as completed** 2017-08-20 21:19 UTC
Labels: enhancement
